[pyprland]
plugins = [
 "scratchpads",
 "shift_monitors",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "alacritty --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "80% 60%"
max_size = "100% 100%"
